config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'
  resources :recipes do
    member do
      post 'favorite'
      delete 'favorite'
    end
  end
  resources :users, only: [:show]
  resources :kitchens, only: [:create, :new, :show, :index] do
    member do
      post 'like'
      delete 'like'
    end
  end
  resources :food_types, only: [:create, :new, :show, :index]
  resources :preferences, only: [:create, :new, :show, :index]
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :recipes
end

app/models/kitchen.rb
class Kitchen < ActiveRecord::Base
  has_many :recipes
  has_and_belongs_to_many :likers, class_name: :User, join_table: :kitchens_users
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  DIFFICULTY_OPTIONS = %w(Fácil Médio Difícil).freeze
  mount_uploader :photo, PhotoUploader
  belongs_to :kitchen
  belongs_to :food_type
  belongs_to :preference
  belongs_to :user
  validates :name, :kitchen_id, :food_type_id, :preference_id, :servings,
            :cook_time, :difficulty, :ingredients, :steps, presence: true

  has_and_belongs_to_many :fans, class_name: :User, join_table: :recipes_users

  def self.most_favorites(order = nil)
    if order == :asc
      all.sort_by { |recipe| recipe.fans.size }
    else
      all.sort_by { |recipe| -recipe.fans.size }
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
  has_and_belongs_to_many :favorites, class_name: :Recipe, join_table: :recipes_users
  has_and_belongs_to_many :likes, class_name: :Kitchen, join_table: :kitchens_users
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  protect_from_forgery with: :exception

  def set_collections
    @kitchens = Kitchen.all
    @food_types = FoodType.all
    @preferences = Preference.all
    @recipes = Recipe.all
  end
end

app/controllers/food_types_controller.rb
class FoodTypesController < ApplicationController
  before_action :set_foodtype, only: :show
  before_action :authenticate_user!, except: :show
  before_action :set_collections, only: :index

  def index
  end

  def new
    @foodtype = FoodType.new
  end

  def create
    if current_user.admin?
      @foodtype = FoodType.create(foodtype_params)
      respond_with @foodtype
    else
      redirect_to root_path, alert: 'You are not allowed to create new food type!'
    end
  end

  def show
    @recipes = Recipe.where(food_type_id: params[:id])
  end

  private

  def foodtype_params
    params.require(:food_type)
          .permit(:name)
  end

  def set_foodtype
    @foodtype = FoodType.find(params[:id])
  end
end

app/controllers/foodtypes_controller.rb
class FoodtypesController < ApplicationController
  before_action :set_foodtype, only: :show
  before_action :authenticate_user!, except: :show

  def new
    @foodtype = FoodType.new
  end

  def create
    if current_user.admin?
      @foodtype = FoodType.create(foodtype_params)
      respond_with @foodtype
    else
      redirect_to root_path
    end
  end

  def show
  end

  private

  def foodtype_params
    params.require(:foodtype)
          .permit(:name)
  end

  def set_foodtype
    @foodtype = FoodType.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_collections, only: :index
  def index
    @favorites = Recipe.most_favorites.first(10)
    @recipes = Recipe.last(20) - @favorites
  end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  before_action :set_kitchen, only: [:show, :like]
  before_action :authenticate_user!, except: :show
  before_action :set_collections, only: :index

  def index
  end

  def new
    @kitchen = Kitchen.new
  end

  def create
    if current_user.admin?
      @kitchen = Kitchen.create(kitchen_params)
      respond_with @kitchen
    else
      redirect_to root_path, alert: 'You are not allowed to create kitchens!'
    end
  end

  def show
    @recipes = Recipe.where(kitchen_id: params[:id])
  end

  def like
    unless @kitchen.likers.exists?(current_user.id)
      @kitchen.likers << current_user
      @kitchen.save
      redirect_to @kitchen, notice: 'Cozinha adicionada as favoritas!'
    else
      @kitchen.likers.delete(current_user)
      @kitchen.save
      redirect_to @kitchen, notice: 'Cozinha removida das favoritas!'
    end
  end

  private

  def kitchen_params
    params.require(:kitchen)
          .permit(:name)
  end

  def set_kitchen
    @kitchen = Kitchen.find(params[:id])
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :set_preference, only: :show
  before_action :authenticate_user!, except: :show
  before_action :set_collections, only: :index

  def index
  end

  def new
    @preference = Preference.new
  end

  def create
    if current_user.admin?
      @preference = Preference.create(preference_params)
      respond_with @preference
    else
      redirect_to root_path, alert: 'You are not allowed to create preferences!'
    end
  end

  def show
    @recipes = Recipe.where(preference_id: params[:id])
  end

  private

  def preference_params
    params.require(:preference)
          .permit(:title)
  end

  def set_preference
    @preference = Preference.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_collections, only: [:new, :create, :edit, :update, :index]
  before_action :set_recipe, except: [:new, :create, :index]
  before_action :authenticate_user!, except: :show

  def index
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.create(recipe_params)
    respond_with @recipe
  end

  def edit
    if current_user.id != @recipe.user_id
      redirect_to root_path, alert: 'You are not allowed to edit that recipe!'
    end
  end

  def update
    @recipe.update(recipe_params)
    respond_with @recipe
  end

  def destroy
    if current_user.id != @recipe.user_id
      redirect_to @recipe, alert: 'You are not allowed to destroy that recipe!'
    else
      @recipe.destroy
      redirect_to root_path, alert: 'Recipe destroyed.'
    end
  end

  def show
  end

  def favorite
    unless @recipe.fans.exists?(current_user.id)
      add_fan
      redirect_to @recipe, notice: 'Receita adicionada as favoritas!'
    else
      remove_fan
      redirect_to @recipe, notice: 'Receita removida das favoritas!'
    end
  end

  private

  def recipe_params
    params.require(:recipe)
          .permit(:name, :kitchen_id, :food_type_id, :preference_id, :servings,
                  :cook_time, :difficulty, :ingredients, :steps, :photo, :photo_cache)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def add_fan
    @recipe.fans << current_user
  end

  def remove_fan
    @recipe.fans.delete(current_user)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :location, :twitter, :facebook, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :location, :twitter, :facebook, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/food_types/_food_type.html.erb
<h4><%= link_to food_type.name, food_type %></h4>
<br>
<hr>

app/views/food_types/_form.html.erb
<span class="error_message"><%= flash[:alert] %></span>
<%= form_for @foodtype do |f| %>
  <div class="form_group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form_group">
    <%= f.submit submit_text, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/food_types/index.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <%= render @food_types %>
    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/food_types/new.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <h1>Novo Tipo de Comida</h1>
      <hr>
      <%= render partial: 'form', locals: { submit_text: 'Criar Tipo de Comida' } %>
    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/food_types/show.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <h2><%= @foodtype.name %></h2>
      <hr>

      <% @recipes.each do |recipe| %>
      <p><%= link_to recipe.name, recipe %></p>
      <p><strong>Kitchen:</strong> <%= recipe.kitchen.name %></p>
      <p><strong>Food type:</strong> <%= recipe.food_type.name%></p>
      <p><strong>Preference:</strong> <%= recipe.preference.title %></p>
      <p><strong>Difficulty:</strong> <%= recipe.difficulty %></p>
      <% end  %>

    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-md-8">
      <h2>Receitas Favoritadas</h2>
      <% @favorites.each do |recipe| %>
        <%= render recipe%>
      <% end  %>
      <h2> Receitas adicionadas recentemente</h2>
        <% @recipes.each do |recipe| %>
        <%= render recipe%>
      <% end  %>
    </div>
    <div id="sidebar" class="col-xs-6 col-md-4">
      <h3> Filtros </h3>
      <h4> Cozinhas </h4>
      <ul style="list-style-type:none">
          <% @kitchens.each do |kitchen| %>
          <li>
          <%= link_to kitchen.name, kitchen_path(kitchen) %>
          </li>
          <% end %>
      </ul>

      <h4> Tipos de Comida </h4>
      <ul style="list-style-type:none">
        <% @food_types.each do |food_type| %>
        <li>
          <%= link_to food_type.name, food_type_path(food_type) %>
        </li>
        <% end %>
      </ul>

      <h4> Preferências </h4>
      <ul style="list-style-type:none">
        <% @preferences.each do |preference| %>
        <li>
          <%= link_to preference.title, preference_path(preference) %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/kitchens/_form.html.erb
<span class="error_message"><%= flash[:alert] %></span>
<%= form_for @kitchen do |f| %>
  <div class="form_group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form_group">
    <%= f.submit submit_text, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/kitchens/_kitchen.html.erb
<h4><%= link_to kitchen.name, kitchen %></h4>
<br>
<hr>

app/views/kitchens/index.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <%= render @kitchens %>
    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/kitchens/new.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <h1>Nova Cozinha</h1>
      <hr>
      <%= render partial: 'form', locals: { submit_text: 'Criar Cozinha' } %>

    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/kitchens/show.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <h2><%= @kitchen.name %></h2>
      <hr>
      <% @recipes.each do |recipe| %>
        <p><%= link_to recipe.name, recipe %></p>
        <p><strong>Kitchen:</strong> <%= recipe.kitchen.name %></p>
        <p><strong>Food type:</strong> <%= recipe.food_type.name%></p>
        <p><strong>Preference:</strong> <%= recipe.preference.title %></p>
        <p><strong>Difficulty:</strong> <%= recipe.difficulty %></p>
      <% end  %>
    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">
      <%= link_to 'Favoritar', like_kitchen_path(@kitchen), method: "post"%><br>
      <%= link_to 'Remover Favorita', like_kitchen_path(@kitchen), method: "delete"%><br>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialRecipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class='navbar navbar-default navbar-fixed-top'>
      <div class='container'>
         <%= link_to 'Social Recipe', root_path, class: 'navbar-brand' %>
         <p class='navbar-text navbar-right'>
            <% if user_signed_in? %>
              <%= link_to ' Olá, ' + current_user.email, user_path(current_user), class:'glyphicon glyphicon-cog'%>
            <% end %>
            <%= link_to ' Sign Up', new_user_registration_path , class:'glyphicon glyphicon-user'%>
            <%= link_to ' Login', new_user_session_path, class:'glyphicon glyphicon-log-in'%>
         </p>
      </div>
    </nav>

  <p class='notice'><%= notice %></p>
  <p class='alert'><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/preferences/_form.html.erb
<span class="error_message"><%= flash[:alert] %></span>
<%= form_for @preference do |f| %>
  <div class="form_group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form_group">
    <%= f.submit submit_text, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/preferences/_preference.html.erb
<h4><%= link_to preference.title, preference %></h4>
<br>
<hr>

app/views/preferences/index.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <%= render @preferences %>
    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/preferences/new.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <h1>Nova Preferência</h1>
      <hr>
      <%= render partial: 'form', locals: { submit_text: 'Criar Preferência' } %>

    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/preferences/show.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <h2><%= @preference.title %></h2>
      <hr>
      <% @recipes.each do |recipe| %>
      <p><%= link_to recipe.name, recipe %></p>
      <p><strong>Kitchen:</strong> <%= recipe.kitchen.name %></p>
      <p><strong>Food type:</strong> <%= recipe.food_type.name%></p>
      <p><strong>Preference:</strong> <%= recipe.preference.title %></p>
      <p><strong>Difficulty:</strong> <%= recipe.difficulty %></p>
      <% end  %>

    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/recipes/_form.html.erb
<span class="error_message"><%= flash[:alert] %></span>
<%= form_for @recipe, html: { multipart: true} do |f| %>
  <div class="form_group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form_group">
    <%= f.label :kitchen_id %>
    <%= f.collection_select :kitchen_id, @kitchens, :id, :name, {prompt: 'Cozinha Gastronônomica'}, {class: "form-control"} %>
  </div>
  <div class="form_group">
    <%= f.label :food_type_id %>
    <%= f.collection_select :food_type_id, @food_types, :id, :name, {prompt: 'Tipo de Comida'}, {class: "form-control"}%>
  </div>
  <div class="form_group">
    <%= f.label :preference_id %>
    <%= f.collection_select :preference_id, @preferences, :id, :title, {prompt: 'Preferência'}, {class: "form-control"} %>
  </div>
  <div class="form_group">
    <%= f.label :servings %>
    <%= f.text_field :servings, class: 'form-control' %>
  </div>
  <div class="form_group">
    <%= f.label :cook_time %>
    <%= f.text_field :cook_time, class: 'form-control' %>
  </div>
  <div class="form_group">
    <%= f.label :difficulty %>
    <%= f.select :difficulty, options_for_select(Recipe::DIFFICULTY_OPTIONS), {prompt: 'Nível de Dificuldade'}, {class: "form-control"} %>
  </div>
  <div class="form_group">
    <%= f.label :ingredients %>
    <%= f.text_area :ingredients, class: 'form-control' %>
  </div>
  <div class="form_group">
    <%= f.label :steps %>
    <%= f.text_area :steps, class: 'form-control' %>
  </div>
  <div class="form_group">
    <%= f.label :photo %>
    <%= f.file_field :photo, class: 'form-control' %>
  </div>
  <div class="form_group">
    <%= f.submit submit_text, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<h4><%= link_to recipe.name, recipe %></h4><br>
<%= image_tag(recipe.photo_url, alt: recipe.name ) %>
<p><strong>Kitchen:</strong> <%= recipe.kitchen.name %></p>
<p><strong>Food type:</strong> <%= recipe.food_type.name%></p>
<p><strong>Preference:</strong> <%= recipe.preference.title %></p>
<p><strong>Difficulty:</strong> <%= recipe.difficulty %></p>
<br>
<hr>

app/views/recipes/edit.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <h1>Editar Receita</h1>
      <hr>
      <%= render partial: 'form', locals: { submit_text: 'Salvar Receita' } %>

    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <%= render @recipes %>
    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <h1>Nova Receita</h1>
      <hr>
      <%= render partial: 'form', locals: { submit_text: 'Criar Receita' } %>

    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <h2><%= @recipe.name %></h2>
      <hr>
      <%= image_tag(@recipe.photo_url, alt: @recipe.name ) %>
      <p><strong>Kitchen:</strong> <%= @recipe.kitchen.name %></p>
      <p><strong>Food type:</strong> <%= @recipe.food_type.name%></p>
      <p><strong>Preference:</strong> <%= @recipe.preference.title %></p>
      <p><strong>Servings:</strong> <%= @recipe.servings %></p>
      <p><strong>Cook time:</strong> <%= @recipe.cook_time %></p>
      <p><strong>Difficulty:</strong> <%= @recipe.difficulty %></p>
      <p><strong>Ingredients:</strong> <%= @recipe.ingredients %></p>
      <p><strong>Steps:</strong> <%= @recipe.steps %></p>

      <%= @recipe.fans.count %> <%= 'Favoritaram' %>

      <%= link_to 'Excluir', recipe_path(@recipe), method: "delete" %><br>
      <%= link_to 'Favoritar', favorite_recipe_path(@recipe), method: "post"%><br>
      <%= link_to 'Remover Favorita', favorite_recipe_path(@recipe), method: "delete"%><br>

    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12 col-sm-6 col-m-8">
      <h2> Cozinhas Favoritas </h2>
      <%= render @user.likes%>
      <h2>Receitas Favoritas</h2>
      <%= render @user.favorites%>
      <h2> Receitas Publicadas </h2>
      <%= render @user.recipes%>
    </div>
    <div id="sidebar" class="col-xs-6 col-m-4">
      <h2><%= @user.name %></h2>
      <p><%= @user.location %></p><br>
      <p><%= @user.email %></p><br>
      <p><%= @user.twitter %></p><br>
      <p><%= @user.facebook %></p><br>
    </div>
  </div>
</div>